name: mo445 # Name of the environment
channels: # Channnels list to search for conda packages
  - conda-forge
  - defaults
  - pytorch
dependencies: # Conda packages
  - graphviz
  - imageio=2.6
  - ipython=7.12
  - ipywidgets=7.5
  - joblib=0.14
  - jupyterlab=1.0.10
  - matplotlib=3.1
  - numexpr=2.7
  - numpy=1.18
  - pandas=1.0
  - pillow=7.0
  - pip
  - psutil=5.7
  - py-xgboost=0.90
  - pydot=1.4
  - pyglet=1.5
  - pyopengl=3.1
  - python=3.7
  - python-graphviz
  - requests=2.22
  - scikit-image=0.16
  - scikit-learn=0.22
  - scipy=1.4
  - tqdm=4.43
  - wheel
  - widgetsnbextension=3.5
  - pip: # Pip packages
    - torch
    - torchvision
    - torch-summary
    - torch-snippets
    - opencv-python==4.2.0.32
    - graphviz
    - pydotplus
    - spacy==2.2.4
    - tensorboard==2.1.1
    - tensorflow-addons==0.8.3
    - tensorflow-data-validation==0.21.5
    - tensorflow-datasets==2.1.0
    - tensorflow-estimator==2.1.0
    - tensorflow-hub==0.7.0
    - tensorflow-metadata==0.21.1
    - tensorflow-model-analysis==0.21.6
    - tensorflow-probability==0.9.0
    - tensorflow-serving-api-gpu==2.1.0
    - tensorflow-transform==0.21.2
    - tensorflow-gpu==2.1.0
    - tf-agents==0.3.0
    - tfx==0.21.2
    - markupsafe==2.0.1