data_path: "../data/registred_images_002/"
data_nlets: "../data/compare_002.txt"
network: "vgg19"
dataloader:
  train_batch: 32
  valid_batch: 32
  num_workers: 1
training:
  image_size: 300
  nchannels: 3
  num_splits: 5
  epochs: 10
  lr: 0.001
  scheduler: "stepLr"
  accum_iter: 1
  verbose_step: 1
  loss:
    margin: 2.0
    contrastive_thresh: 1.1
wandb: False