epochs: 200
batch_size: 32
path_to_save_model: "../models/fingerprint_conv_margin_1/"
path_to_save_report: "../report/fingerprint_conv_margin_1/"
wandb: False
network: conv_fingerprint_paper_m1

test:
  batch_size: 1
  verbose: 1

model:
  ConvFingerprintSiamese:
    input_size: !!python/list [100, 100]
    activation: True

train_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/cropped_images_v3_train/"
    compare_file: "../compare_files/compare_splited_v3_train_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

validation_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/cropped_images_v3_validation/"
    compare_file: "../compare_files/compare_splited_v3_validation_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

test_dataset:
  BasicDataset:
    images_folder: "../data/cropped_images_v3_test/"
    compare_file: "../compare_files/compare_splited_v3_test_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB

transformation:
  BasicTransformations:
    image_size: !!python/list [100, 100]
    affine_degrees: 5
    affine_translate: !!python/tuple [0.01, 0.02]
    affine_scale: !!python/tuple [0.9, 1.1]

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0.01

loss:
  ContrastiveLoss:
    margin: 1.0
    contrastive_threshold: 1.1