epochs: 100
batch_size: 32
path_to_save_model: "../models/fingerprint_conv_cropped_dl_1/"
path_to_save_report: "../report/fingerprint_conv_cropped_dl_1/"
wandb: True
network: fingerprint_conv_cropped_dl_1

test:
  batch_size: 1
  verbose: 1

model:
  ConvFingerprintSiamese:
    input_size: !!python/list [140, 140]
    activation: True

train_dataset:
  BalancedCroppedDataset:
    images_folder: "../data/images_02_cropped/"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    subset_images: "../compare_files/train.txt"
    repeat: 4

validation_dataset:
  BalancedCroppedDataset:
    images_folder: "../data/images_02_cropped/"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    subset_images: "../compare_files/validation.txt"
    repeat: 4

test_dataset:
  BasicDataset:
    images_folder: "../data/cropped_images_v3_test/"
    compare_file: "../compare_files/compare_splited_v3_test_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB

transformation:
  BasicTransformations:
    image_size: !!python/list [140, 140]
    affine_degrees: 5
    affine_translate: !!python/tuple [0.01, 0.02]
    affine_scale: !!python/tuple [0.9, 1.1]
    rotate_degrees: 45

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0

loss:
  ContrastiveLoss:
    margin: 2.0
    contrastive_threshold: 1.1