epochs: 10
batch_size: 64
path_to_save_model: "../models/fingerprint_conv_cropped_dl_1/"
path_to_save_report: "../report/fingerprint_conv_cropped_dl_1/"
wandb: False
network: efficientnet_b0

test:
  batch_size: 1
  verbose: 1

model:
  #ConvFingerprintSiamese:
  #  input_size: !!python/list [200, 200]
  #  activation: True
  SiameseNetworkTimmBackbone:
    network:  efficientnet_b0 #"xcit_small_24_p8_224"
    image_size: 200
    nchannels: 3
    transformers: False


train_dataset:
  BalancedCroppedDataset:
    images_folder: "../data/images_02_cropped/"
    transform: BasicTransformations
    mode: 1 # 0: gray scale | 1: RGB
    subset_images: "../compare_files/train.txt"
    repeat: 4

validation_dataset:
  BalancedCroppedDataset:
    images_folder: "../data/images_02_cropped/"
    transform: BasicTransformations
    mode: 1 # 0: gray scale | 1: RGB
    subset_images: "../compare_files/validation.txt"
    repeat: 4

test_dataset:
  BalancedCroppedDataset:
    images_folder: "../data/images_02_cropped/"
    transform: BasicTransformations
    mode: 1 # 0: gray scale | 1: RGB
    subset_images: "../compare_files/test.txt"

    repeat: 1


transformation:
  BasicTransformations:
    image_size: !!python/list [200, 200]
    affine_degrees: 5
    affine_translate: !!python/tuple [0.01, 0.02]
    affine_scale: !!python/tuple [0.9, 1.1]
    rotate_degrees: 45
  Albumentation:
      image_size: 200
      custom_transform: False # only for BasicStratifiedDatasetAlbumentation
optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0

loss:
  ContrastiveLoss:
    margin: 2.0
    contrastive_threshold: 1.1