epochs: 10
batch_size: 64
path_to_save_model: "../models/"
path_to_save_report: "../report/dataset_v1/"
wandb: False
network: "efficientnet_b0"

model:
  SiameseNetworkTimmBackbone:
    network:  efficientnet_b0 #"xcit_small_24_p8_224"
    image_size: 200
    nchannels: 3
    transformers: False
  #SimpleConvSiameseNN:
  #  input_size: !!python/tuple [200, 200]


train_dataset:
  BalancedCroppedDataset:
    images_folder: "../data/images_02_cropped/"
    transform: null
    mode: 0 # 0: gray scale | 1: RGB
    subset_images: "../compare_files/train.txt"
    repeat: 4

validation_dataset:
  BalancedCroppedDataset:
    images_folder: "../data/images_02_cropped/"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    subset_images: "../compare_files/validation.txt"
    repeat: 4

test_dataset:
  BasicDataset:
    images_folder: "../data/cropped_images_v3_test/"
    compare_file: "../compare_files/compare_splited_v3_test_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB

transformation:
  BasicTransformations:
    image_size: !!python/list [140, 140]
    affine_degrees: 20
    affine_translate: !!python/tuple [0.1, 0.4]
    affine_scale: !!python/tuple [0.6, 1.4]
    rotate_degrees: 45

test:
  batch_size: 1
  verbose: 1

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0.01

loss:
  ContrastiveLoss:
    margin: 2
    contrastive_threshold: 1.1
