epochs: 200
batch_size: 32
path_to_save_model: "../models/first_model.pth"
path_to_save_report: "../report/dataset_v1/"

model:
  ViTSiamese:
    in_channels: 1
    patch_size: 16
    emb_size: 768
    img_size: 120
    depth: 5

  SimpleConvSiameseNN:
    input_size: !!python/list [120, 120]


train_dataset:
  BasicDataset:
    images_folder: "../data/registred_images_v1_train/"
    compare_file: "../compare_files/compare_splited_v1_train_new.txt"
    transform: BasicTransformations

validation_dataset:
  BasicDataset:
    images_folder: "../data/registred_images_v1_validation/"
    compare_file: "../compare_files/compare_splited_v1_validation_new.txt"
    transform: BasicTransformations

transformation:
  BasicTransformations:
    image_size: !!python/list [120, 120]
    affine_degrees: 5
    affine_translate: !!python/tuple [0.01, 0.02]
    affine_scale: !!python/tuple [0.9, 1.1]

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0.01

loss:
  ContrastiveLoss:
    margin: 2.0
    contrastive_threshold: 1.1