epochs: 10
batch_size: 64
path_to_save_model: "/mnt/arquivos_linux/1_semestre/Falcao/image_analysis_final_project/src_phase_2/models/"
path_to_save_report: "../report/dataset_v1/"
wandb: True
network: "efficientnet_b0"

model:
  #SiameseNetworkTimmBackbone:
  #  network:  efficientnet_b1 #"xcit_small_24_p8_224"
  #  image_size: 200
  #  nchannels: 3
  #  transformers: False
  SimpleConvSiameseNN:
    input_size: !!python/tuple [200, 200]


train_dataset:
  BasicStratifiedDatasetAlbumentation:
    images_folder: "../data/registred_images_v2_train/"
    compare_file: "../compare_files/compare_splited_v2_train_new.txt"
    transform: Albumentation
    mode: 1 # 0: gray scale | 1: RGB
    stratify_each_epoch: True
    test: False

validation_dataset:
  BasicStratifiedDatasetAlbumentation:
    images_folder: "../data/registred_images_v2_validation/"
    compare_file: "../compare_files/compare_splited_v2_validation_new.txt"
    transform: Albumentation
    mode: 1 # 0: gray scale | 1: RGB
    stratify_each_epoch: True
    test: False

test_dataset:
  BasicStratifiedDatasetAlbumentation:
    images_folder: "../data/registred_images_v2_test/"
    compare_file: "../compare_files/compare_splited_v2_test_new.txt"
    transform: Albumentation
    mode: 1 # 0: gray scale | 1: RGB
    stratify_each_epoch: True
    test: True

transformation:
  BasicTransformations:
    image_size: !!python/list [120, 120]
    affine_degrees: 5
    affine_translate: !!python/tuple [0.01, 0.02]
    affine_scale: !!python/tuple [0.9, 1.1]
  Albumentation:
    image_size: 200
    custom_transform: enhancement # only for BasicStratifiedDatasetAlbumentation

test:
  batch_size: 1
  verbose: 1

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0.01

loss:
  ContrastiveLoss:
    margin: 2
    contrastive_threshold: 1.1