epochs: 200
batch_size: 32
path_to_save_model: "../models/first_model_v2_dlfix.pth"
path_to_save_report: "../report/dataset_v2_dlfix/"
wandb: True

model:
  SimpleConvSiameseNN:
    input_size: !!python/list [120, 120]

train_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/registred_images_v2_train/"
    compare_file: "../compare_files/compare_splited_v2_train_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

validation_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/registred_images_v2_validation/"
    compare_file: "../compare_files/compare_splited_v2_validation_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

transformation:
  BasicTransformations:
    image_size: !!python/list [120, 120]
    affine_degrees: 5
    affine_translate: !!python/tuple [0.01, 0.02]
    affine_scale: !!python/tuple [0.9, 1.1]

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0.01

loss:
  ContrastiveLoss:
    margin: 2.0
    contrastive_threshold: 1.1