epochs: 200
batch_size: 32
path_to_save_model: "../models/first_model_vgg.pth"
path_to_save_report: "../report/dataset_v1_vgg/"

model: PreTrainedVGGSiameseNN

train_dataset:
  BasicDataset:
    images_folder: "../data/registred_images_v1_train/"
    compare_file: "../compare_files/compare_splited_v1_train_new.txt"
    transform: BasicTransformations
    mode: 1 # 0: gray scale | 1: RGB

validation_dataset:
  BasicDataset:
    images_folder: "../data/registred_images_v1_validation/"
    compare_file: "../compare_files/compare_splited_v1_validation_new.txt"
    transform: BasicTransformations
    mode: 1 # 0: gray scale | 1: RGB

transformation:
  BasicTransformations:
    image_size: !!python/list [120, 120]
    affine_degrees: 5
    affine_translate: !!python/tuple [0.01, 0.02]
    affine_scale: !!python/tuple [0.9, 1.1]

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0.01

loss:
  ContrastiveLoss:
    margin: 2.0
    contrastive_threshold: 1.1