epochs: 50
batch_size: 16
path_to_save_model: "/mnt/arquivos_linux/1_semestre/Falcao/image_analysis_final_project/src_phase_2/models/"
path_to_save_report: "../report/dataset_v1/"
network: "vit_data_balanced_crop_project_1"
wandb: True

test:
  batch_size: 16

model:
  ViTSiamese:
    in_channels: 1
    patch_size: 16
    emb_size: 768
    img_size: 240
    depth: 4


train_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/cropped_images_v3_train/"
    compare_file: "../compare_files/compare_splited_v3_train_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

validation_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/cropped_images_v3_validation/"
    compare_file: "../compare_files/compare_splited_v3_validation_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

test_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/cropped_images_v3_test/"
    compare_file: "../compare_files/compare_splited_v3_test_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

transformation:
  BasicTransformations:
    image_size: !!python/list [240, 240]
    affine_degrees: 5
    affine_translate: !!python/tuple [0.01, 0.02]
    affine_scale: !!python/tuple [0.9, 1.1]

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0.01

loss:
  ContrastiveLoss:
    margin: 2.0
    contrastive_threshold: 1.1