epochs: 2000
batch_size: 64
path_to_save_model: "/mnt/arquivos_linux/1_semestre/Falcao/image_analysis_final_project/src_phase_2/models/vit_model_siamese.pth"
path_to_save_report: "../report/dataset_v1/"
wandb: False

model:
  ViTSiameseTriplet:
    in_channels: 1
    patch_size: 16
    emb_size: 768
    img_size: 120
    depth: 4


train_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/registred_images_v1_train/"
    compare_file: "../compare_files/compare_splited_v1_train_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

validation_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/registred_images_v1_validation/"
    compare_file: "../compare_files/compare_splited_v1_validation_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

transformation:
  BasicTransformations:
    image_size: !!python/list [120, 120]
    affine_degrees: 5
    affine_translate: !!python/tuple [0.01, 0.02]
    affine_scale: !!python/tuple [0.9, 1.1]

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0.01

loss:
  TripletLoss:
    margin: 2.0