epochs: 1
batch_size: 32
path_to_save_model: "../models/SimpleConvSiameseNN_dataset_v1/"
path_to_save_report: "../report/SimpleConvSiameseNN_dataset_v1/"
wandb: False
network: SimpleConvSiameseNN_dataset_v1

test:
  batch_size: 1
  verbose: 1

model:
  SimpleConvSiameseNN:
    input_size: !!python/list [140, 140]

train_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/registred_images_v1_train/"
    compare_file: "../compare_files/compare_splited_v1_train_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

validation_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/registred_images_v1_validation/"
    compare_file: "../compare_files/compare_splited_v1_validation_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

test_dataset:
  BasicStratifiedDataset:
    images_folder: "../data/registred_images_v1_test/"
    compare_file: "../compare_files/compare_splited_v1_test_new.txt"
    transform: BasicTransformations
    mode: 0 # 0: gray scale | 1: RGB
    stratify_each_epoch: True

transformation:
  BasicTransformations:
    image_size: !!python/list [140, 140]
    affine_degrees: 10
    affine_translate: !!python/tuple [0.01, 0.2]
    affine_scale: !!python/tuple [0.8, 1.2]
    rotate_degrees: 45
    gaussian_blur_kernel: !!python/tuple [3, 3]
    random_erasing_p: 0.5
    random_erasing_scale: !!python/tuple [0.02, 0.3]

optimizer:
  Adam:
    lr: 0.001
    weight_decay: 0

loss:
  ContrastiveLoss:
    margin: 2.0
    contrastive_threshold: 1.1